FROM node:18.12.0 AS build

ENV NODE_ENV development
WORKDIR /app

COPY package.json .
COPY package-lock.json .
RUN npm ci --silent
RUN npm install react-scripts@5.0.1 -g --silent
COPY . .

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]